name: CI/CD Pipeline for VetCare Website to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js for linting and testing tools
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies for linting and testing
      - name: Install Dependencies
        run: npm install -g htmlhint stylelint stylelint-config-standard

      # Validate HTML
      - name: Lint HTML
        run: htmlhint index.html

      # Validate CSS
      - name: Lint CSS
        run: stylelint "styles.css"

      # Optional: Run accessibility checks using pa11y
      - name: Install pa11y
        run: npm install -g pa11y
      - name: Start Local Server
        run: npm install -g http-server && http-server . -p 8080 &
      - name: Accessibility Check
        run: pa11y http://localhost:8080
        continue-on-error: true # Accessibility issues won't fail the build

      # Build step (copy files to a build directory)
      - name: Build
        run: |
          mkdir -p build
          cp index.html styles.css build/
          cp *.jfif build/ # Copy images referenced in HTML

      # Upload build artifacts for deployment
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build/

      # Set up Node.js for Netlify CLI
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Deploy to Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=build
